import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val fragment: String = "androidx.fragment:fragment:" + Versions.fragment

    const val com_android_databinding_adapters: String = "com.android.databinding:adapters:" +
            Versions.com_android_databinding

    /**
     * https://developer.android.com/studio
     */
    const val baselibrary: String = "com.android.databinding:baseLibrary:" +
            Versions.com_android_databinding

    /**
     * http://tools.android.com
     */
    const val com_android_databinding_compiler: String = "com.android.databinding:compiler:" +
            Versions.com_android_databinding

    const val library: String = "com.android.databinding:library:" +
            Versions.com_android_databinding

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val customtabs: String = "com.android.support:customtabs:" + Versions.customtabs

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val crashlytics: String = "com.crashlytics.sdk.android:crashlytics:" +
            Versions.crashlytics

    /**
     * https://github.com/davemorrissey/subsampling-scale-image-view
     */
    const val subsampling_scale_image_view: String =
            "com.davemorrissey.labs:subsampling-scale-image-view:" +
            Versions.subsampling_scale_image_view

    /**
     * https://github.com/deano2390/MaterialShowcaseView
     */
    const val materialshowcaseview: String = "com.github.deano2390:MaterialShowcaseView:" +
            Versions.materialshowcaseview

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://github.com/google/gson
     */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * https://github.com/google/dagger
     */
    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger
     */
    const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

    const val firebase_core: String = "com.google.firebase:firebase-core:" + Versions.firebase_core

    const val firebase_messaging: String = "com.google.firebase:firebase-messaging:" +
            Versions.firebase_messaging

    const val firebase_perf: String = "com.google.firebase:firebase-perf:" + Versions.firebase_perf

    const val perf_plugin: String = "com.google.firebase:perf-plugin:" + Versions.perf_plugin

    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    const val picasso2_okhttp3_downloader: String =
            "com.jakewharton.picasso:picasso2-okhttp3-downloader:" +
            Versions.picasso2_okhttp3_downloader

    /**
     * https://github.com/JakeWharton/ThreeTenABP/
     */
    const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" +
            Versions.threetenabp

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://github.com/mikepenz/AboutLibraries
     */
    const val aboutlibraries: String = "com.mikepenz:aboutlibraries:" + Versions.aboutlibraries

    const val com_patloew_navigationviewfragmentadapters_adapters: String =
            "com.patloew.navigationviewfragmentadapters:adapters:" +
            Versions.com_patloew_navigationviewfragmentadapters_adapters

    /**
     * https://github.com/pinterest/ktlint
     */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * https://github.com/timusus/RecyclerView-FastScroll
     */
    const val recyclerview_fastscroll: String = "com.simplecityapps:recyclerview-fastscroll:" +
            Versions.recyclerview_fastscroll

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android_no_op: String =
            "com.squareup.leakcanary:leakcanary-android-no-op:" + Versions.com_squareup_leakcanary

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.com_squareup_leakcanary

    /**
     * https://github.com/square/okhttp
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp
     */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/picasso/
     */
    const val picasso: String = "com.squareup.picasso:picasso:" + Versions.picasso

    /**
     * https://github.com/square/retrofit/
     */
    const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/tbruyelle/RxPermissions
     */
    const val rxpermissions: String = "com.tbruyelle.rxpermissions2:rxpermissions:" +
            Versions.rxpermissions

    const val buildsrcversions: String = "de.fayard:buildSrcVersions:" + Versions.buildsrcversions

    const val io_fabric_tools_gradle: String = "io.fabric.tools:gradle:" +
            Versions.io_fabric_tools_gradle

    /**
     * https://github.com/ReactiveX/RxAndroid
     */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxJava
     */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * https://github.com/ReactiveX/RxKotlin
     */
    const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:" + Versions.rxkotlin

    const val realm_android_kotlin_extensions: String =
            "io.realm:realm-android-kotlin-extensions:" + Versions.io_realm

    const val realm_android_library: String = "io.realm:realm-android-library:" + Versions.io_realm

    /**
     * http://realm.io
     */
    const val realm_annotations_processor: String = "io.realm:realm-annotations-processor:" +
            Versions.io_realm

    /**
     * http://realm.io
     */
    const val realm_annotations: String = "io.realm:realm-annotations:" + Versions.io_realm

    /**
     * http://realm.io
     */
    const val realm_gradle_plugin: String = "io.realm:realm-gradle-plugin:" + Versions.io_realm

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://jsoup.org/
     */
    const val jsoup: String = "org.jsoup:jsoup:" + Versions.jsoup
}
